name: "Check TypeScript Errors Action"
description: "Check TypeScript errors and compare them with the base branch"
author: "Arhia"
icon: box
inputs:
  repo-token:
    description: "Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}"
    required: true
  directory:
    description: "Directory to run install and build in. Default is '.'"
    default: "."
  files-changed:
    description: "List of files changed in the current PR (separated by space). Use action 'futuratrepadeira/changed-files'"
    default: ""
  files-added:
    description: "List of files added in the current PR (separated by space). Use action 'futuratrepadeira/changed-files'"
    default: ""
  files-deleted:
    description: "List of files deleted in the current PR (separated by space). Use action 'futuratrepadeira/changed-files'"
    default: ""
  line-numbers:
    description: "List of files with added and removed lines. Use action 'Equip-Collaboration/diff-line-numbers'"
  ts-config-path:
    description: "Path of tsconfig file. Default is './tsconfig.json'"
    default: "./tsconfig.json"
  use-check:
    description: "Report status as a CI Check"
  check-fail-mode:
    description: "Allowed values: added, errors_in_pr, errors_in_code"
    required: true
  output-behaviour:
    description: "Allowed values: comment, annotate, both"
    default: "comment"
  comment-behaviour:
    description: "Allowed values: new, edit"
    default: "new"
  debug:
    description: "Set true to log TypeScript errors in base branch and pull request branch"
    default: false
runs:
  using: "node16"
  main: "dist/index.js"
