name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  repo-token:
    description: 'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
